### ISSUE TITLE
Accommodation for pds4file, convert `associated_abspaths`

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-pdsfile#10]
From rms-webtools created by [juzen2003](https://github.com/juzen2003): SETI/rms-webtools#63  

- In `Pds4File/pdsfile.py`, convert `associated_abspaths` function to list all the associated absolute paths of a pdsfile instance.

**Comment by juzen2003** [comment]
Fixed by [pull #17 ](https://github.com/SETI/rms-pdsfile/pull/17)
